Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'

Style/BracesAroundHashParameters:
  Enabled: false

CyclomaticComplexity:
  Max: 7

AsciiComments:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false
