language: ruby

before_install:
  - bundle install --path=vendor/bundle --bin-stubs
#  - apt-get update && apt-get -y install mysql-client
#  - gem install mysql2 toml-rb net-ssh-gateway rubocop

script:
  - ./bin/rubocop lib
  - bundle exec ruby lib/qrunner.rb
